import React from 'react';
import Head from 'next/head';

import { getLayout } from '@/components/layouts/MainLayout';

export const HomePage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>HomePage</div>
    </>
  );
};

HomePage.getLayout = getLayout;

export default HomePage;
